### ISSUE TITLE
Can't eat while wearing skull bandana

### ISSUE THREAD

**Issue by Hamblinius** [Goob-Station/Goob-Station#375]
## Description
As the title says, you can't eat while wearing the skull bandana and get a prompt to remove it before being able to eat.

**Reproduction**
1. Exist on Goob
2. Wear skull bandana
3. Try to eat

**Screenshots**
![](https://files.catbox.moe/j6d86n.png)

**Additional context**
I'm too lazy to PR it myself pls fix :)

**Comment by Hamblinius** [comment]
Oh by the way I checked other bandanas it's just the skull one.

**Comment by a-person5660** [comment]
the botany bandana also does this

**Comment by jorgun** [comment]
base bandana has ` - type: IngestionBlocker`
this shud be a problem whit all bandanas as they all have the same base.
this shud only be a problem when it is folded

skullbandana contains no code indicating any diffrenece from sey red bandana, they shud be the same.
other then sprite
```
- type: entity
  parent: ClothingMaskBandanaBase
  id: ClothingMaskBandSkull
  name: skull bandana
  description: A bandana with a skull to make you look even cooler.
  components:
  - type: Sprite
    sprite: Clothing/Head/Bandanas/skull.rsi
  - type: Clothing
    sprite: Clothing/Head/Bandanas/skull.rsi

```
