### ISSUE TITLE
port delta-v nukie-med-hud

### ISSUE THREAD

**Issue by JoeHammad1844** [Goob-Station/Goob-Station#376]
## Description

on delta V there exists a special eyewear for nukie medics that has both nukie and med hud, this needs to be ported

**Comment by Verbalase** [comment]
The Secmed HUD I think it's called?

**Comment by jorgun** [comment]
this is already implemented

```
- type: entity
  parent: [ClothingEyesBase, ShowSecurityIcons]
  id: ClothingEyesHudSyndicateAgent
  name: syndicate agent visor
  description: The Syndicate Agent's professional heads-up display, designed for quick diagnosis of their team's status.
  components:
  - type: Sprite
    sprite: Clothing/Eyes/Hud/syndagent.rsi
  - type: Clothing
    sprite: Clothing/Eyes/Hud/syndagent.rsi
  - type: ShowSyndicateIcons
  - type: ShowHealthBars
    damageContainers:
    - Biological
```
